system:
  # 결재시스템의 system id (법인마다 구분 필요 일단 테스트서버는 BMIL로 등록됨)
  system_id: 'BMIL' 
server:
  host: 0.0.0.0
  port: 8081
vsmgmt:
  host: 127.0.0.1
  port: 8000
vshr:
  host: 127.0.0.1
  port: 8100
wsdl:
  path: ./approval_status.wsdl
