services:
  approval_server:
    hostname: approval_server
    container_name: approval_server
    image: docker.lab.somansa.com/lgen-approval-server:latest
    restart: always
    environment:
      NODE_ENV: "dev"
      TZ: "Asia/Seoul"
    volumes:
      - "./config.yaml:/approval_server/config.yaml"
      - "./approval_status.wsdl:/approval_server/approval_status.wsdl"
    ports:
      - "8081:8081"
      
